- name: Transfer and execute a script.
  hosts: server2
  remote_user: ansible
  become: true
  tasks:
     - name: Transfer the script
       copy: src=./script.sh dest=/home/ansible mode=0777

     - name: Execute the script
       command: sh /home/ansible/script.sh